#!/usr/bin/env bash

this_folder="${XDG_CONFIG_HOME:-$HOME/.config}"

fonts_folder=$HOME/.fonts

login() {
    read -p "What is your current login manager? [ENTER = gdm]: " old_login_manager 
    if [ "$old_login_manager" == "" ]
    then
        old_login_manager=gdm
    fi
    echo "You selected $old_login_manager" &&
    sleep 1 &&
    read -p "What do you want your new login manager to be? [ENTER = ly]: " new_login_manager 
    if [ "$new_login_manager" == "" ]
    then
        new_login_manager=ly
    fi
    echo "You selected $new_login_manager" &&
    sleep 1 &&
    read -p "Are you sure you want to replace $old_login_manager with $new_login_manager? [y/N]: " input
    case $input in
        "y" | "Y" |"yes" | "Yes" | "YES")
            echo "Installing $new_login_manager. Input your password once prompted. Please don't close this terminal until I'm done pls. Thx" &&
            sleep 3 &&
            sudo pacman -S $new_login_manager &&
            sudo systemctl disable $old_login_manager &&
            sudo systemctl enable $new_login_manager
        ;;
        *) 
            echo "Aight, Fam. We're good. No changes were made."
            return
        ;;
    esac
}

folders() {
    cd
    list=$HOME/.config/folders.txt

    while read -r line; do
        if [ ! -d ~/$line ]
        then
            echo "Made $line folder"
            mkdir ~/$line
        else
            echo "$line already exists"
	    fi
    done <$list
}

get-fonts() {
    if [ ! -d "$fonts_folder" ]
    then
        mkdir $fonts_folder
    fi
    if [ ! -d "$fonts_folder/MaterialDesign-Font" ]
    then
        cd $fonts_folder &&
        git clone https://github.com/Templarian/MaterialDesign-Font.git --depth 1 &&
        cd $this_folder
    else
        cd $fonts_folder/MaterialDesign-Font &&
        git pull &&
        cd $this_folder
    fi
    if [ ! -d "$fonts_folder/devicon" ]
    then
        cd $fonts_folder &&
        git clone https://github.com/devicons/devicon.git --depth 1 &&
        cd $this_folder
    else
        cd $fonts_folder/devicon &&
        git pull &&
        cd $this_folder
    fi
    cp $fonts_folder/MaterialDesign-Font/MaterialDesignIconsDesktop.ttf $fonts_folder &&
    
    cp $fonts_folder/devicon/fonts/devicon.ttf $fonts_folder &&

    cp $this_folder/fonts/* $fonts_folder
}

update-rc() {
    cp $this_folder/home/.* $HOME
}

dependencies() {
    sudo pacman -S - < dependencies.txt &&
    bash aur-helper.sh
}

case $1 in
    fonts)
        get-fonts
    ;;
    rc) 
        update-rc
    ;;
    depend)
        dependencies
    ;;
    all)
        update-rc &&
        get-fonts &&
        dependencies
    ;;
    *)
        echo "Pick an option:"
        echo "1) Update current fonts"
        echo "2) Update your RC files"
        echo "3) Grab all dependencies"
        echo "4) All of the above"
        read -p "What do you want to do? [1, 2, 3, 4]: " response
        case $response in
            1)
                get-fonts
            ;;
            2) 
                update-rc
            ;;
            4)
                update-rc &&
                get-fonts
            ;;
            *)
                return 2>/dev/null
            ;;
        esac
    ;;
esac
