#!/usr/bin/env bash

this_folder="${XDG_CONFIG_HOME:-$HOME/.config}"
build="$this_folder/build"

#-----------------------------------------------

folders() {
    cd
    list=$HOME/.config/folders.txt

    while read -r line; do
        if [ ! -d ~/$line ]
        then
            echo "Made $line folder"
            mkdir ~/$line
        else
            echo "$line already exists"
	    fi
    done <$list
}

update-login() {
    read -p "What is your current login manager? [ENTER = sddm]: " old_login_manager 
    if [ "$old_login_manager" == "" ]
    then
        old_login_manager=sddm
    fi
    echo "You selected $old_login_manager" &&
    sleep 1 &&
    read -p "What do you want your new login manager to be? [ENTER = ly]: " new_login_manager 
    if [ "$new_login_manager" == "" ]
    then
        new_login_manager=ly
    fi
    echo "You selected $new_login_manager" &&
    sleep 1 &&
    read -p "Are you sure you want to replace $old_login_manager with $new_login_manager? [Y/n]: " input
    case $input in
        "" | "y" | "Y" | "yes" | "Yes" | "YES")
            echo "Installing $new_login_manager. Input your password once prompted. Please don't close this terminal until I'm done pls. Thx" &&
            sleep 3 &&
            sudo pacman -S $new_login_manager &&
            sudo systemctl disable $old_login_manager &&
            sudo systemctl enable $new_login_manager
        ;;
        *) 
            echo "Aight, Fam. We're good. No changes were made."
            return
        ;;
    esac
}

login() {
    read -p "What login manager would you like to use? [ENTER = sddm]: " login_manager 
    if [ "$login_manager" == "" ]
    then
        login_manager=sddm
    fi
    echo "You've selected $login_manager" &&
    sleep 1
    read -p "Is this what you want? [Y/n]: " input
    case $input in
        "" | "y" | "Y" | "yes" | "Yes" | "YES")
            echo "Installing $login_manager. Input your password once prompted. Please don't close this terminal until I'm done pls. Thx" &&
            sleep 3 &&
            sudo pacman -S $login_manager &&
            sudo systemctl enable $login_manager
        ;;
        *) 
            echo "Aight, Fam. We're good. No changes were made."
            return
        ;;
    esac
}

#-----------------------------------------------

read -p "Do you already have a login manager? [y/N]: " answer
case $answer in
    "" | "n" | "N" | "no" | "No" | "NO")
        login
    ;;
    "y" | "Y" | "yes" | "Yes" | "YES")
        update-login
    ;;
    *)
        echo "Please answer with yes or no"
    ;;
esac
bash $build all &&
folders &&
git clone https://github.com/ALEX-DAWSON/my.nvim.git $this_folder/nvim
