#!/usr/bin/env bash

. ~/.cache/wal/colors.sh

selected=$(cliphist list | dmenu -c -p "Clipboard:" -nb $color0 -nf $color6 -sb $color3 -sf $color7 -fn Pangolin -l 5 | cliphist decode)

if [ -n $selected ]
then 
    exit 0
else
    wl-copy "$selected"
    notify-send --app-name="Clipboard" "Copied $selected"
fi
