#!/usr/bin/env bash

. $HOME/.cache/wal/colors.sh
hypr_folder="$HOME/.config/hypr"

KEYS="$hypr_folder/keybindings.conf"
PROGRAMS="$hypr_folder/prog-defaults.conf"

terminal=$(grep "terminal" $PROGRAMS | sed 's/ //g' | awk -F = '{print $2}')
fileManager=$(grep "fileManager" $PROGRAMS | sed 's/ //g' | awk -F = '{print $2}')
menu=$(grep "menu" $PROGRAMS | sed 's/ //2' | awk -F = '{print $2}')
browser=$(grep "browser" $PROGRAMS | sed 's/ //2' | awk -F = '{print $2}')
power=$(grep "power" $PROGRAMS | sed -e 's/ //2' | awk -F = '{print $2}')

mapfile -t BINDINGS < <(grep '^bind = ' "$KEYS" | \
    sed -e 's/   */ /g' -e 's/bind = //g' -e 's/, /,/g' -e 's/#/,/' | \
    awk -F, '{cmd=""; for(i=3;i<NF;i++) cmd=cmd $(i) " ";print $1 " + " $2 "  " $NF " , " cmd " \\n"}')

CHOICE=$(echo -e "${BINDINGS[@]}" | dmenu -c -nb $color0 -nf $color6 -sb $color3 -sf $color7 -fn Pangolin -l 5 -p "Keybindings:" || exit 0)

CMD=$(echo "$CHOICE" | awk -F, '{print $2}' | sed 's/ //')

# echo $terminal
# echo $CMD
# execute it if first word is exec else use hyprctl dispatch
if [[ $CMD == exec* ]]; then
    echo "eval $CMD"
    eval "$CMD"
else
    HYPRCMD=$(echo "$CMD" | sed -e 's/  $//' -e 's/ $//')
    echo "hyprctl dispatch $HYPRCMD"
    hyprctl dispatch "$HYPRCMD"
fi
