#!/bin/bash

screenshots_folder=$HOME/Pictures/screenshots

prompt="Screenshot"

entries="󰣌 Screen\n 󰭩 Selection\n 󰞥 Window\n 󰜺 Cancel"

if [ ! -d $screenshots_folder ]
then
    mkdir $screenshots_folder
    echo "Made directory $screenshots_folder" 
fi

# ------ CREDIT ------
# equk 2023 - equk.co.uk
#
# https://github.com/equk/dotfiles
# ------ CREDIT ------

monitor() {
    # Take screenshot of current active monitor
    sleep 1
    active_workspace_monitor=$(hyprctl -j activeworkspace | jq -r '(.monitor)')
    screenshot_filename="$screenshots_folder/$(date +"%d-%m-%Y-%H%S")-$active_workspace_monitor.png"

    grim -o $active_workspace_monitor $screenshot_filename

    if [ -e $screenshot_filename ]; then
        notify-send -i $screenshot_filename "Grim" "Active Monitor Screenshot Saved \n $screenshot_filename"
    fi
}

window() {
    # Take screenshot of current active window

    active_window_class=$(hyprctl -j activewindow | jq -r '(.class)')
    screenshot_filename="$HOME/Pictures/screenshots/$(date +"%d-%m-%Y-%H%S")-$active_window_class.png"

    sleep 1

    hyprctl -j activewindow | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"' | grim -g - $screenshot_filename

    if [ -e $screenshot_filename ]; then
        notify-send -i $screenshot_filename "Grim" "Active Window Screenshot Saved \n $screenshot_filename"
    fi
}

selection() {
    # Take screenshot of selection

    screenshot_filename="$screenshots_folder/$(date +"%d-%m-%Y-%H%S")-Selection.png"
    grim -g "$(slurp)" $screenshot_filename

    if [ -e $screenshot_filename ]; then
        notify-send -i $screenshot_filename "Grim" "Selection Screenshot Saved \n $screenshot_filename"
    fi
}

case $1 in
    screen)
        monitor 
    ;;
    selection)
        selection
    ;;
    window)
        window
    ;;
    cancel)
        exit
    ;;
    *)
        selected=$(echo -e $entries|wofi -p $prompt -L 5 -c ~/.config/wofi/config-menu| awk '{print tolower($2)}')
        case $selected in
            screen)
                monitor 
            ;;
            selection)
                selection
            ;;
            window)
                window
            ;;
            cancel)
                exit
            ;;
        esac
    ;;
esac
